services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10


  n8n:
    image: docker.n8n.io/n8nio/n8n:2.32.7
    restart: unless-stopped

    ports:
      - "127.0.0.1:${N8N_PORT}:5678"

    environment:
      # n8n internal PostgreSQL database
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: "5432"
      DB_POSTGRESDB_DATABASE: ${POSTGRES_DB}
      DB_POSTGRESDB_USER: ${POSTGRES_USER}
      DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD}

      # n8n instance configuration
      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
      N8N_HOST: ${N8N_HOST}
      N8N_PORT: "5678"
      N8N_PROTOCOL: ${N8N_PROTOCOL}

      # Cloudflare public URL
      WEBHOOK_URL: "${N8N_PUBLIC_URL}/"
      N8N_EDITOR_BASE_URL: ${N8N_PUBLIC_URL}
      N8N_PROXY_HOPS: "1"

      # Time zone
      GENERIC_TIMEZONE: Asia/Manila
      TZ: Asia/Manila

      # Runtime settings
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
      N8N_RUNNERS_ENABLED: "true"

      # Execution-history cleanup
      EXECUTIONS_DATA_PRUNE: "true"
      EXECUTIONS_DATA_MAX_AGE: "336"

      # Security hardening
      N8N_COMMUNITY_PACKAGES_ENABLED: "false"
      N8N_PUBLIC_API_DISABLED: "true"
      N8N_DIAGNOSTICS_ENABLED: "false"
      N8N_TEMPLATES_ENABLED: "false"

    volumes:
      - n8n_data:/home/node/.n8n

    depends_on:
      postgres:
        condition: service_healthy
  
  gotenberg:
    image: gotenberg/gotenberg:8-chromium
    restart: unless-stopped


volumes:
  postgres_data:
  n8n_data: